import { createHordeClient } from "./ai-horde.js";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const scenes = {
  sculpture: {
    title: "Liquid poetry",
    image: "./assets/sculpture.png",
    alt: "An organic flower made from flowing bronze ribbons",
    prompt:
      "An organic sculptural bloom in brushed bronze, dramatic studio lighting, a quiet black background.",
  },
  landscape: {
    title: "Somewhere beyond",
    image: "./assets/landscape.jpg",
    alt: "A mountain range rising through atmospheric clouds",
    prompt:
      "A cinematic mountain landscape above the clouds, soft early morning light, a quiet sense of scale and wonder.",
  },
  architecture: {
    title: "Space to imagine",
    image: "./assets/architecture.jpg",
    alt: "Contemporary architecture with sculptural flowing curves",
    prompt:
      "Fluid architectural forms, sculptural lines and soft natural light. Minimal, considered, and quietly monumental.",
  },
};
const drafts = new Map();
const generatedImages = new Map();
const horde = createHordeClient();
let activeGeneration = null;
let currentScene = "sculpture";
let lastFocus = null;
const studio = $("#studio-dialog");
const film = $("#film-dialog");
const info = $("#info-dialog");

function openDialog(dialog) {
  lastFocus = document.activeElement;
  closeMenu();
  dialog.showModal();
  document.body.classList.add("modal-open");
}
function closeDialog(dialog) {
  dialog.close();
}
$$("dialog").forEach((dialog) => {
  $("[data-close]", dialog).addEventListener("click", () =>
    closeDialog(dialog),
  );
  dialog.addEventListener("click", (event) => {
    if (event.target !== dialog) return;
    const box = dialog.getBoundingClientRect();
    if (
      event.clientX < box.left ||
      event.clientX > box.right ||
      event.clientY < box.top ||
      event.clientY > box.bottom
    )
      closeDialog(dialog);
  });
  dialog.addEventListener("close", () => {
    document.body.classList.remove("modal-open");
    lastFocus?.focus({ preventScroll: true });
  });
});

function chooseScene(key) {
  drafts.set(currentScene, $("#creative-prompt").value);
  currentScene = key;
  const scene = scenes[key];
  const image = $("#studio-image");
  const generated = generatedImages.get(key);
  image.src = generated?.src ?? scene.image;
  image.alt = generated ? `AI-generated image: ${generated.prompt}` : scene.alt;
  $("#scene-title").textContent = generated
    ? "Your imagination, realized."
    : scene.title;
  $("#image-kind").textContent = generated
    ? `AI · ${generated.model}`
    : "Curated preview";
  $(".studio-output").classList.toggle("generated", Boolean(generated));
  $("#creative-prompt").value = drafts.get(key) ?? scene.prompt;
  const download = $("#download-image");
  download.href = generated?.src ?? scene.image;
  download.download = generated
    ? `aura-${key}-ai.webp`
    : `aura-${key}.${key === "sculpture" ? "png" : "jpg"}`;
  $$("[data-pick]").forEach((button) => {
    const active = button.dataset.pick === key;
    button.classList.toggle("active", active);
    button.setAttribute("aria-pressed", String(active));
  });
  if (!activeGeneration) setStudioStatus("");
}
function openStudio(key = currentScene, plan) {
  chooseScene(key);
  $("#studio-plan").textContent = plan
    ? `${plan} · Plan preview`
    : "A space for your next idea";
  openDialog(studio);
}
$$("[data-open-studio]").forEach((button) =>
  button.addEventListener("click", () => openStudio()),
);
$$("[data-scene]").forEach((button) =>
  button.addEventListener("click", () => openStudio(button.dataset.scene)),
);
$$("[data-pick]").forEach((button) =>
  button.addEventListener("click", () => chooseScene(button.dataset.pick)),
);
$$("[data-plan]").forEach((button) =>
  button.addEventListener("click", () =>
    openStudio(currentScene, button.dataset.plan),
  ),
);

$("#save-brief").addEventListener("click", () => {
  const prompt = $("#creative-prompt").value.trim();
  if (!prompt) {
    setStudioStatus(
      "Add a little direction to your creative brief first.",
      true,
    );
    $("#creative-prompt").focus();
    return;
  }
  const generated = generatedImages.get(currentScene);
  const imageDetails = generated
    ? `Reference image generated by AI Horde.\nModel: ${generated.model}\nSeed: ${generated.seed}\nPrompt used for that image: ${generated.prompt}`
    : "The reference image is a curated preview.";
  const content = `AURA / Creative brief\n\nDirection: ${scenes[currentScene].title}\n\nCurrent brief:\n${prompt}\n\n${imageDetails}\n`;
  const url = URL.createObjectURL(
    new Blob([content], { type: "text/plain;charset=utf-8" }),
  );
  const link = document.createElement("a");
  link.href = url;
  link.download = `aura-${currentScene}-brief.txt`;
  document.body.append(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  setStudioStatus("Your creative brief is ready to download.");
});

function setStudioStatus(message, error = false) {
  $("#studio-status").textContent = message;
  $("#studio-status").dataset.error = String(error);
}

function setGenerationBusy(busy) {
  $$(
    "[data-pick], #ai-model, #creative-prompt, #ai-consent, #generate-image",
  ).forEach((control) => {
    control.disabled = busy;
  });
  $("#cancel-generation").hidden = !busy;
  $("#cancel-generation").disabled = false;
  $("#cancel-generation").textContent = "Cancel";
  $("#ai-progress").hidden = !busy;
  $(".studio-output").setAttribute("aria-busy", String(busy));
  $("#generate-image span").textContent = busy ? "Creating…" : "Generate image";
}

function showGenerationProgress(status) {
  let message;
  if (status.phase === "submitting")
    message = "Sending your idea to the free queue…";
  else if (status.phase === "reconnecting")
    message =
      "Waiting for the service to respond. Your request is still active…";
  else if (status.phase === "generating")
    message = "A volunteer GPU is creating your image…";
  else if (status.slow)
    message =
      "The free queue is moving slowly. You can keep waiting or cancel.";
  else {
    message = "Waiting for a volunteer GPU";
    if (status.position !== null)
      message += ` · community queue position ${status.position}`;
    if (status.estimate > 0)
      message += ` · about ${Math.ceil(status.estimate / 60)} min (estimate)`;
  }
  $("#ai-progress-text").textContent = message;
}

$("#generate-image").addEventListener("click", async () => {
  if (activeGeneration) return;
  const prompt = $("#creative-prompt").value.trim();
  if (!prompt) {
    setStudioStatus(
      "Write a description of the image you want to create.",
      true,
    );
    $("#creative-prompt").focus();
    return;
  }
  if (!$("#ai-consent").checked) {
    setStudioStatus(
      "Read and tick the AI Horde sharing agreement before generating.",
      true,
    );
    $("#ai-consent").focus();
    return;
  }
  const operation = { controller: new AbortController(), scene: currentScene };
  activeGeneration = operation;
  setStudioStatus("");
  setGenerationBusy(true);
  try {
    const result = await horde.generateImage({
      prompt,
      model: $("#ai-model").value,
      signal: operation.controller.signal,
      onProgress: showGenerationProgress,
    });
    if (operation.controller.signal.aborted) return;
    const preview = new Image();
    preview.src = result.src;
    try {
      await preview.decode();
    } catch {
      throw new Error(
        "The AI service returned an image the browser could not open. Please try again.",
      );
    }
    if (operation.controller.signal.aborted) return;
    generatedImages.set(operation.scene, result);
    chooseScene(operation.scene);
    setStudioStatus(
      `Image ready · ${result.model}. Download it to keep a copy.`,
    );
  } catch (error) {
    if (error.name === "AbortError") {
      setStudioStatus(
        error.remoteCancelled
          ? "Request cancelled. No new image was saved."
          : "Stopped waiting. The service may still finish a request already in progress.",
      );
    } else {
      setStudioStatus(
        error.message ||
          "The AI service could not create this image. Please try again.",
        true,
      );
    }
  } finally {
    if (activeGeneration === operation) {
      activeGeneration = null;
      setGenerationBusy(false);
    }
  }
});

function cancelGeneration() {
  if (!activeGeneration) return;
  $("#cancel-generation").disabled = true;
  $("#cancel-generation").textContent = "Cancelling…";
  $("#ai-progress-text").textContent = "Cancelling the community request…";
  activeGeneration.controller.abort();
}
$("#cancel-generation").addEventListener("click", cancelGeneration);
studio.addEventListener("close", cancelGeneration);

$$("[data-billing]").forEach((button) =>
  button.addEventListener("click", () => {
    const annual = button.dataset.billing === "annual";
    $$("[data-billing]").forEach((option) => {
      const active = option === button;
      option.classList.toggle("active", active);
      option.setAttribute("aria-pressed", String(active));
    });
    $('[data-price="pro"]').textContent = annual ? "19.20" : "24";
    $('[data-price="studio"]').textContent = annual ? "47.20" : "59";
    $('[data-billing-note="pro"]').textContent = annual
      ? "$230.40 billed yearly · Concept plan"
      : "$24 billed monthly · Concept plan";
    $('[data-billing-note="studio"]').textContent = annual
      ? "$566.40 billed yearly · Concept plan"
      : "$59 billed monthly · Concept plan";
  }),
);

function openFilm() {
  const reduceMotion = matchMedia("(prefers-reduced-motion: reduce)").matches;
  $(".film-frame").classList.toggle("paused", reduceMotion);
  $("#film-toggle").textContent = reduceMotion
    ? "Reduced motion enabled"
    : "Pause animation";
  $("#film-toggle").disabled = reduceMotion;
  openDialog(film);
}
$("#watch-film").addEventListener("click", openFilm);
$$("[data-film]").forEach((button) =>
  button.addEventListener("click", openFilm),
);
$("#film-toggle").addEventListener("click", () => {
  const paused = $(".film-frame").classList.toggle("paused");
  $("#film-toggle").textContent = paused ? "Play animation" : "Pause animation";
});

const menuToggle = $(".menu-toggle");
function closeMenu() {
  $("#mobile-nav").hidden = true;
  menuToggle.setAttribute("aria-expanded", "false");
  menuToggle.setAttribute("aria-label", "Open menu");
}
menuToggle.addEventListener("click", () => {
  const open = menuToggle.getAttribute("aria-expanded") !== "true";
  menuToggle.setAttribute("aria-expanded", String(open));
  menuToggle.setAttribute("aria-label", open ? "Close menu" : "Open menu");
  $("#mobile-nav").hidden = !open;
});
$$(".mobile-nav a").forEach((link) =>
  link.addEventListener("click", closeMenu),
);
document.addEventListener("keydown", (event) => {
  if (event.key === "Escape") closeMenu();
});
matchMedia("(min-width: 761px)").addEventListener("change", (event) => {
  if (event.matches) closeMenu();
});

$("#digest-form").addEventListener("submit", (event) => {
  event.preventDefault();
  $("#digest-status").textContent =
    "The digest is coming soon. Your email has not been sent or saved.";
  $("#digest-form").reset();
});
$$("[data-info]").forEach((button) =>
  button.addEventListener("click", () => {
    const privacy = button.dataset.info === "privacy";
    $("#info-title").textContent = privacy
      ? "Your ideas stay yours."
      : "An idea, made tangible.";
    $("#info-body").textContent = privacy
      ? "AURA has no analytics, cookies, or browser storage. Briefs and generated results stay in this tab until you save them. Pressing Generate image sends your prompt and connection information to AI Horde, whose volunteer workers process it. Anonymous generated images are shared with LAION for AI training; the studio requires you to acknowledge this before sending a request. Do not include private information in prompts. The digest does not send or store emails. GitHub Pages and AI Horde apply their own hosting and privacy policies."
      : "AURA is an independent creative studio by Akmal Zokirjonov. Free image generation uses Stable Diffusion and Deliberate through AI Horde's volunteer network, with no account or private API key. Availability and waiting time depend on the community queue. Pricing illustrates a potential product; paid subscriptions, AI video generation, team collaboration, and email delivery are not connected. Studio photography is illustrative.";
    openDialog(info);
  }),
);
$("#year").textContent = new Date().getFullYear();

function drawConnections() {
  const canvas = $("#neural-canvas");
  const origin = canvas.getBoundingClientRect();
  const center = $(".central-node").getBoundingClientRect();
  const group = $("#connection-paths");
  group.replaceChildren();
  $$("[data-node]", canvas).forEach((satellite) => {
    const node = $(".node-port", satellite).getBoundingClientRect();
    const left = satellite.dataset.node === "left";
    const fromX = node.left + node.width / 2 - origin.left;
    const fromY = node.top + node.height / 2 - origin.top;
    const toX = (left ? center.left : center.right) - origin.left;
    const toY = center.top + center.height / 2 - origin.top;
    const curve = Math.max(38, Math.abs(toX - fromX) * 0.65);
    const direction = left ? 1 : -1;
    const d = `M ${fromX} ${fromY} C ${fromX + curve * direction} ${fromY}, ${toX - curve * direction} ${toY}, ${toX} ${toY}`;
    ["node-line", "node-flow"].forEach((name) => {
      const path = document.createElementNS(
        "http://www.w3.org/2000/svg",
        "path",
      );
      path.setAttribute("d", d);
      path.setAttribute("class", name);
      group.append(path);
    });
  });
}
let connectionFrame;
const scheduleConnections = () => {
  cancelAnimationFrame(connectionFrame);
  connectionFrame = requestAnimationFrame(drawConnections);
};
new ResizeObserver(scheduleConnections).observe($("#neural-canvas"));
window.addEventListener("load", scheduleConnections);
document.fonts.ready.then(scheduleConnections);
$$(".satellite").forEach((card) => {
  card.addEventListener("transitionend", scheduleConnections);
});
